/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Tag {
  id: string
  name: string
  type: string
  line: number
  path: string
  dependencies: Array<string>
}
export interface SearchResult {
  tag: Tag
  score: number
}
export declare function sum(a: number, b: number): number
export declare function scanCodebase(root: string): Promise<Array<Tag>>
/**
 * A simple, high-performance graph store for code symbols.
*/
export declare class SymbolGraph {
  constructor()
  addNode(tag: Tag): void
  getImpactedFiles(symbolName: string): Array<string>
  clear(): void
}
/**
 * A simple, high-performance vector store for code tags.
*/
export declare class VectorStore {
  constructor()
  /**
  * Add a tag with its embedding vector.
  */
  add(tag: Tag, embedding: Array<number>): void
  /**
  * Perform a semantic search using cosine similarity.
  */
  search(queryEmbedding: Array<number>, limit: number): Array<SearchResult>
  clear(): void
  size(): number
}
