import type { OfficialPluginManifest } from "./types"

export const OFFICIAL_PLUGINS: OfficialPluginManifest[] = [
  {
    id: "code-review",
    name: "Code Review",
    description: "Automated code review for pull requests using multiple specialized subagents with confidence-based scoring",
    version: "1.0.0",
    author: { name: "Anthropic", email: "support@anthropic.com" },
    category: "review",
    commands: ["code-review"],
  },
  {
    id: "code-simplifier",
    name: "Code Simplifier",
    description: "Simplifies and refines code for clarity, consistency, and maintainability while preserving exact behavior",
    version: "1.0.0",
    author: { name: "Anthropic", email: "support@anthropic.com" },
    category: "development",
    agents: ["code-simplifier"],
    commands: ["code-simplifier"],
  },
  {
    id: "feature-dev",
    name: "Feature Development",
    description: "Guided 7-phase feature development workflow with codebase exploration and architecture blueprints",
    version: "1.0.0",
    author: { name: "Anthropic", email: "support@anthropic.com" },
    category: "development",
    agents: ["code-architect", "code-explorer", "code-reviewer"],
    commands: ["feature-dev"],
  },
  {
    id: "pr-review-toolkit",
    name: "PR Review Toolkit",
    description: "Comprehensive PR review suite with 6 specialized review agents (tests, errors, comments, types, simplification)",
    version: "1.0.0",
    author: { name: "Anthropic", email: "support@anthropic.com" },
    category: "review",
    agents: [
      "code-reviewer",
      "code-simplifier",
      "comment-analyzer",
      "pr-test-analyzer",
      "silent-failure-hunter",
      "type-design-analyzer",
    ],
    commands: ["review-pr"],
  },
  {
    id: "commit-commands",
    name: "Commit Commands",
    description: "Git commit workflows: clean conventional commits, commit-push-PR creation, and gone branch cleanup",
    version: "1.0.0",
    author: { name: "Anthropic", email: "support@anthropic.com" },
    category: "git",
    commands: ["commit", "commit-push-pr", "clean_gone"],
  },
  {
    id: "frontend-design",
    name: "Frontend Design",
    description: "Elite visual and UI/UX design guidance: typography, custom color palettes, responsive layouts, and non-generic aesthetics",
    version: "1.0.0",
    author: { name: "Anthropic", email: "support@anthropic.com" },
    category: "development",
    skills: ["frontend-design"],
  },
  {
    id: "skill-creator",
    name: "Skill Creator",
    description: "End-to-end skill creation, iteration, evaluation, benchmarking, and packaging toolkit",
    version: "1.0.0",
    author: { name: "Anthropic", email: "support@anthropic.com" },
    category: "creation",
    skills: ["skill-creator"],
    agents: ["analyzer", "comparator", "grader"],
  },
  {
    id: "hookify",
    name: "Hookify",
    description: "Turns conversation corrections, user feedback, or instructions into deterministic rules and hooks",
    version: "1.0.0",
    author: { name: "Anthropic", email: "support@anthropic.com" },
    category: "workflow",
    skills: ["writing-rules"],
    agents: ["conversation-analyzer"],
    commands: ["hookify", "list", "help"],
  },
  {
    id: "code-modernization",
    name: "Code Modernization",
    description: "Comprehensive legacy codebase modernization, architecture analysis, business rules extraction, and uplift migration",
    version: "1.0.0",
    author: { name: "Anthropic", email: "support@anthropic.com" },
    category: "development",
    agents: [
      "architecture-critic",
      "business-rules-extractor",
      "legacy-analyst",
      "scaffolder",
      "security-auditor",
      "test-engineer",
      "uplift-migrator",
      "version-delta-analyst",
    ],
    commands: [
      "modernize",
      "modernize-assess",
      "modernize-brief",
      "modernize-extract-rules",
      "modernize-harden",
      "modernize-map",
      "modernize-preflight",
      "modernize-reimagine",
      "modernize-review",
      "modernize-status",
      "modernize-transform",
      "modernize-uplift",
      "modernize-verify",
    ],
  },
  {
    id: "mcp-server-dev",
    name: "MCP Server Development",
    description: "Skills for designing, building, and deploying Model Context Protocol (MCP) servers, apps, and bundles",
    version: "1.0.0",
    author: { name: "Anthropic", email: "support@anthropic.com" },
    category: "mcp",
    skills: ["build-mcp-server", "build-mcp-app", "build-mcpb"],
  },
  {
    id: "mcp-tunnels",
    name: "MCP Tunnels",
    description: "Docker-based secure tunneling for local and remote MCP servers",
    version: "1.0.0",
    author: { name: "Anthropic", email: "support@anthropic.com" },
    category: "mcp",
    commands: ["create-docker-mcp-tunnel"],
  },
  {
    id: "plugin-dev",
    name: "Plugin Development",
    description: "Complete authoring suite for plugins, skills, agents, commands, hooks, and MCP integrations",
    version: "1.0.0",
    author: { name: "Anthropic", email: "support@anthropic.com" },
    category: "creation",
    skills: [
      "agent-development",
      "command-development",
      "hook-development",
      "mcp-integration",
      "plugin-settings",
      "plugin-structure",
      "skill-development",
    ],
    agents: ["agent-creator", "plugin-validator", "skill-reviewer"],
    commands: ["create-plugin"],
  },
  {
    id: "playground",
    name: "Playground",
    description: "Interactive visual playground, component prototyping, concept mapping, and diff review",
    version: "1.0.0",
    author: { name: "Anthropic", email: "support@anthropic.com" },
    category: "development",
    skills: ["playground"],
  },
  {
    id: "project-artifact",
    name: "Project Artifacts",
    description: "Generates structured software engineering artifacts, system blueprints, and architecture dashboards",
    version: "1.0.0",
    author: { name: "Anthropic", email: "support@anthropic.com" },
    category: "development",
    skills: ["project-artifact"],
  },
  {
    id: "security-guidance",
    name: "Security Guidance",
    description: "Application security rules, vulnerability prevention, sensitive data exposure checks, and reminders",
    version: "1.0.0",
    author: { name: "Anthropic", email: "support@anthropic.com" },
    category: "security",
  },
  {
    id: "session-report",
    name: "Session Report",
    description: "Session analytics, tool usage telemetry, token efficiency, and completion reports",
    version: "1.0.0",
    author: { name: "Anthropic", email: "support@anthropic.com" },
    category: "workflow",
    skills: ["session-report"],
  },
  {
    id: "ralph-loop",
    name: "Ralph Loop",
    description: "Autonomous self-correcting development loop with task verification and stop hooks",
    version: "1.0.0",
    author: { name: "Anthropic", email: "support@anthropic.com" },
    category: "workflow",
    commands: ["ralph-loop", "cancel-ralph"],
  },
  {
    id: "receipts",
    name: "Receipts",
    description: "Cryptographically verifiable task receipts and transcript mining",
    version: "1.0.0",
    author: { name: "Anthropic", email: "support@anthropic.com" },
    category: "workflow",
    skills: ["receipts"],
  },
  {
    id: "agent-sdk-dev",
    name: "Agent SDK Development",
    description: "Tools and verification agents for developing autonomous agent applications using the Agent SDK",
    version: "1.0.0",
    author: { name: "Anthropic", email: "support@anthropic.com" },
    category: "creation",
    agents: ["agent-sdk-verifier-ts", "agent-sdk-verifier-py"],
    commands: ["new-sdk-app"],
  },
  {
    id: "claude-security",
    name: "Security Vulnerability Scanner",
    description: "Vulnerability scanning, dependency audit, patch generation, and patch verification",
    version: "1.0.0",
    author: { name: "Anthropic", email: "support@anthropic.com" },
    category: "security",
    skills: ["claude-security"],
    agents: ["scan-inventory", "scan-loader", "scan-researcher", "scan-verifier", "patch-generator", "patch-verifier"],
  },
  {
    id: "claude-md-management",
    name: "Repository Rules Management",
    description: "Audit, revise, and optimize project guidelines, AGENTS.md, and rules files",
    version: "1.0.0",
    author: { name: "Anthropic", email: "support@anthropic.com" },
    category: "workflow",
    skills: ["claude-md-improver"],
    commands: ["revise-claude-md"],
  },
  {
    id: "claude-code-setup",
    name: "Project Automation Recommender",
    description: "Analyzes project structure and recommends tailored scripts, tools, and automation skills",
    version: "1.0.0",
    author: { name: "Anthropic", email: "support@anthropic.com" },
    category: "workflow",
    skills: ["claude-automation-recommender"],
  },
  {
    id: "cwc-makers",
    name: "Maker & Hardware Assistant",
    description: "Embedded hardware development and onboarding (Cardputer, M5Stack, ESP32)",
    version: "1.0.0",
    author: { name: "Anthropic", email: "support@anthropic.com" },
    category: "development",
    skills: ["cardputer-buddy", "m5-onboard"],
    commands: ["maker-setup"],
  },
  {
    id: "math-olympiad",
    name: "Math Olympiad",
    description: "Rigorous step-by-step mathematical reasoning, Olympiad-level proofs, and formal verification",
    version: "1.0.0",
    author: { name: "Anthropic", email: "support@anthropic.com" },
    category: "education",
    skills: ["math-olympiad"],
  },
  {
    id: "explanatory-output-style",
    name: "Explanatory Output Style",
    description: "Clear, conceptual explanations breaking down complex technical decisions and rationale",
    version: "1.0.0",
    author: { name: "Anthropic", email: "support@anthropic.com" },
    category: "education",
  },
  {
    id: "learning-output-style",
    name: "Learning Output Style",
    description: "Educational output formatting designed to guide users through concepts interactively",
    version: "1.0.0",
    author: { name: "Anthropic", email: "support@anthropic.com" },
    category: "education",
  },
  {
    id: "example-plugin",
    name: "Example Plugin",
    description: "Reference example demonstrating plugin manifests, commands, skills, and MCP configuration",
    version: "1.0.0",
    author: { name: "Anthropic", email: "support@anthropic.com" },
    category: "creation",
    skills: ["example-skill", "example-command"],
    commands: ["example-command"],
  },
  {
    id: "typescript-lsp",
    name: "TypeScript Language Server",
    description: "TypeScript/JavaScript language server configuration and intelligence guidance",
    version: "1.0.0",
    author: { name: "Anthropic", email: "support@anthropic.com" },
    category: "lsp",
    lsp: {
      language: "typescript",
      extensions: [".ts", ".tsx", ".js", ".jsx", ".mts", ".cts", ".mjs", ".cjs"],
      serverPackage: "typescript-language-server",
    },
  },
  {
    id: "pyright-lsp",
    name: "Pyright Language Server",
    description: "Python type checking and language intelligence guidance via Pyright",
    version: "1.0.0",
    author: { name: "Anthropic", email: "support@anthropic.com" },
    category: "lsp",
    lsp: {
      language: "python",
      extensions: [".py", ".pyi"],
      serverPackage: "pyright",
    },
  },
  {
    id: "gopls-lsp",
    name: "Go Language Server (gopls)",
    description: "Go code intelligence, refactoring, and navigation guidance via gopls",
    version: "1.0.0",
    author: { name: "Anthropic", email: "support@anthropic.com" },
    category: "lsp",
    lsp: {
      language: "go",
      extensions: [".go"],
      serverPackage: "golang.org/x/tools/gopls",
    },
  },
  {
    id: "rust-analyzer-lsp",
    name: "Rust Analyzer",
    description: "Rust code intelligence, semantic analysis, and cargo integration via rust-analyzer",
    version: "1.0.0",
    author: { name: "Anthropic", email: "support@anthropic.com" },
    category: "lsp",
    lsp: {
      language: "rust",
      extensions: [".rs"],
      serverPackage: "rust-analyzer",
    },
  },
  {
    id: "clangd-lsp",
    name: "Clangd Language Server",
    description: "C/C++ language server guidance providing fast code navigation and diagnostics",
    version: "1.0.0",
    author: { name: "Anthropic", email: "support@anthropic.com" },
    category: "lsp",
    lsp: {
      language: "c-cpp",
      extensions: [".c", ".cpp", ".cc", ".cxx", ".h", ".hpp"],
      serverPackage: "clangd",
    },
  },
  {
    id: "csharp-lsp",
    name: "C# Language Server (OmniSharp)",
    description: "C# language server configuration and development intelligence",
    version: "1.0.0",
    author: { name: "Anthropic", email: "support@anthropic.com" },
    category: "lsp",
    lsp: {
      language: "csharp",
      extensions: [".cs"],
      serverPackage: "omnisharp",
    },
  },
  {
    id: "jdtls-lsp",
    name: "Java Language Server (JDTLS)",
    description: "Eclipse JDT Language Server guidance for Java development",
    version: "1.0.0",
    author: { name: "Anthropic", email: "support@anthropic.com" },
    category: "lsp",
    lsp: {
      language: "java",
      extensions: [".java"],
      serverPackage: "jdtls",
    },
  },
  {
    id: "kotlin-lsp",
    name: "Kotlin Language Server",
    description: "Kotlin language server guidance for Gradle/Maven projects",
    version: "1.0.0",
    author: { name: "Anthropic", email: "support@anthropic.com" },
    category: "lsp",
    lsp: {
      language: "kotlin",
      extensions: [".kt", ".kts"],
      serverPackage: "kotlin-language-server",
    },
  },
  {
    id: "lua-lsp",
    name: "Lua Language Server",
    description: "Lua language server guidance for Lua scripts and Neovim/game configs",
    version: "1.0.0",
    author: { name: "Anthropic", email: "support@anthropic.com" },
    category: "lsp",
    lsp: {
      language: "lua",
      extensions: [".lua"],
      serverPackage: "lua-language-server",
    },
  },
  {
    id: "php-lsp",
    name: "PHP Language Server (Intelephense)",
    description: "PHP language server guidance providing fast completion and analysis",
    version: "1.0.0",
    author: { name: "Anthropic", email: "support@anthropic.com" },
    category: "lsp",
    lsp: {
      language: "php",
      extensions: [".php"],
      serverPackage: "intelephense",
    },
  },
  {
    id: "ruby-lsp",
    name: "Ruby Language Server",
    description: "Ruby LSP guidance for Rails and standard Ruby projects",
    version: "1.0.0",
    author: { name: "Anthropic", email: "support@anthropic.com" },
    category: "lsp",
    lsp: {
      language: "ruby",
      extensions: [".rb", ".rake"],
      serverPackage: "ruby-lsp",
    },
  },
  {
    id: "swift-lsp",
    name: "Swift Language Server (SourceKit-LSP)",
    description: "SourceKit-LSP guidance for Swift and C-family languages on macOS and Linux",
    version: "1.0.0",
    author: { name: "Anthropic", email: "support@anthropic.com" },
    category: "lsp",
    lsp: {
      language: "swift",
      extensions: [".swift"],
      serverPackage: "sourcekit-lsp",
    },
  },
  {
    id: "skill-up",
    name: "Skill-Up (Alibaba)",
    description: "Evaluates Agent Skills, agents, and workspaces. Drives continuous Skill evolution through declarative cases and regression loops",
    version: "1.0.0",
    author: { name: "Alibaba", url: "https://github.com/alibaba/skill-up" },
    category: "workflow",
    skills: ["skill-upper"],
    commands: ["skill-up"],
  },
]
